import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "../components/navigationBar";
import MobileNavbar from "../components/mobilenavbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="w-full lg:pl-4 mx-[auto] h-screen flex md:flex-row flex-col">
          {/* Sidebar / Mobile Navbar */}
          <div className="hidden md:flex lg:w-65 md:w-63 h-full pl-8">
            <NavBar />
          </div>
          <div className="md:hidden border-1 border-[var(--border)]">
            <MobileNavbar />
          </div>

          {/* Main content */}
          <main className="flex-1 md:p-4 lg:pr-4 px-4 my-2 overflow-auto ">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
